spring:
  datasource:
    type: org.apache.tomcat.jdbc.pool.DataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.2.226:3306/mail-db?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 12345678
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          # 自动创建表
          auto: update
  cloud:
    # stream相关配置
    stream:
      default:
        # 消息内容序列化格式
        contentType: application/json
      # 通道设置
      bindings:
        # 订单事件
        order-event:
          binder: mq1
          # 消费者分组，每个组只消费一次，防止重复消费
          group: mail
      # 具体接入的mq实现 
      binders:
        # 命名为mq1，使用rabbitmq
        mq1:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 192.168.99.100
                port: 5672
                username: guest
                password: guest